on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'
      
jobs:
  sweep-experiments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - run: npm i -g gulp cli
      - run: npm ci
      - run: gulp sweep-experiments
      - uses: peter-evans/create-pull-request@v3
