on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  sweep-experiments:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup-node
        uses: actions/setup-node@v2.1.2

      - name: run
        run: |
          npm ci
          npx gulp sweep-experiments --skip_lint_fix
          git log -1 --format=%b

      - name: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 🚮 Sweep experiments
