# Executes `gulp sweep-experiments` every monday.
# If experiments are swept, a PR is created.

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  sweep-experiments:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup-node
        uses: actions/setup-node@v2.1.2

      - name: run
        run: |
          npm ci
          npx gulp sweep-experiments --skip_lint_fix
          echo "::set-output name=subject::$(git log 1 --format=%s)"
          echo "::set-output name=body::$(git log 1 --format=%b)"

      - name: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ steps.run.outputs.subject }}
          body: ${{ steps.run.outputs.body }}
