# Executes `gulp sweep-experiments` every monday.
# If experiments are swept, a PR is created.

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  sweep-experiments:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup-node
        uses: actions/setup-node@v2.1.2

      - name: run
        id: run
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          npm ci
          npx gulp sweep-experiments --skip_lint_fix
          
          export title=$(git log -1 --format=%s)
          body="${title%\"}"
          body="${title#\"}"

          export body=$(git log -1 --format=%b)
          body="${body%\"}"
          body="${body#\"}"
          
          export hash=$(git log -1 --format=%h)
          hash="${hash%\"}"
          hash="${hash#\"}"

          echo "::set-output name=title::$(echo "$title")"
          echo "::set-output name=body::$(echo "$body")"
          echo "::set-output name=branch::$(echo sweep-experiments-"$hash")"

      - name: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          draft: true
          title: ${{ steps.run.outputs.title }}
          body: ${{ steps.run.outputs.body }}
          branch: ${{ steps.run.outputs.branch }}
