on:
  schedule:
    - cron: '*/5 * * * *'
      
jobs:
  sweep-experiments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: gulp sweep-experiments
        run: gulp sweep-experiments

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
